import re, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

# 1. Read existing products-data.js
with open(r'C:\Catalago Prodent\website\js\products-data.js', encoding='utf-8') as f:
    content = f.read()

existing_ids = set(re.findall(r"id:'([^']+)'", content))
print(f"IDs existentes: {len(existing_ids)}")

# 2. Vamasa: extraer entradas del archivo generado
with open(r'C:\Catalago Prodent\website\vamasa_new_products.js', encoding='utf-8') as f:
    vamasa_raw = f.read()

vamasa_lines = [line.strip() for line in vamasa_raw.split('\n')
                if line.strip().startswith("{id:'vamasa-")]
vamasa_block = ""
for line in vamasa_lines:
    m = re.search(r"id:'([^']+)'", line)
    if m and m.group(1) not in existing_ids:
        vamasa_block += "  " + line.rstrip(',') + ",\n"

print(f"Vamasa nuevos: {vamasa_block.count(chr(39)+'vamasa-')}")

# 3. Primadent block (brand:'orthopremium')
primadent_block = """\
  {id:'pdm-parafil-lab', code:'PD003', cat:'primadent', brand:'orthopremium', name:'Parafil LAB — Composite Zirconio Laboratorio', unit:'jeringa 4.5g', img:'imagenes/primadent/pag_07.jpg', desc:'Composite fotopolimerizable de nano-particulas de zirconia para restauraciones indirectas: coronas, inlays, onlays, carillas e implantes.', specs:['Resistencia 450 MPa','31 colores disponibles','Codigo PD003']},
  {id:'pdm-parafil-lab-kit4', code:'PD002', cat:'primadent', brand:'orthopremium', name:'Parafil LAB Kit 4 Jeringas', unit:'kit', img:'imagenes/primadent/pag_08.jpg', desc:'Kit Parafil LAB 4 jeringas (A2, A3, B2, T), 2 jeringas Stain cafe y naranja, adhesivo, grabador en gel, 2 mezcladores, colorimetro e instructivo.', specs:['4 x 4.5g jeringas','Adhesivo fotocurable incluido','Codigo PD002']},
  {id:'pdm-parafil-lab-kit10', code:'PD001', cat:'primadent', brand:'orthopremium', name:'Parafil LAB Kit 10 Jeringas + Kit Completo', unit:'kit', img:'imagenes/primadent/pag_08.jpg', desc:'Kit completo Parafil LAB: 10 jeringas, 8 jeringas Stain, opacadores, gingiva, gel separador, modelador, primer y accesorios. 50 agujas.', specs:['10 x 4.5g jeringas','Kit completo con colorimetro','Codigo PD001']},
  {id:'pdm-parafil-lab-opaque', code:'PD004', cat:'primadent', brand:'orthopremium', name:'Parafil LAB Foundation Opaque Universal', unit:'frasco', img:'imagenes/primadent/pag_09.jpg', desc:'Opacador universal para uso con Parafil LAB en restauraciones sobre metal. Mascara el metal y crea base para la estratificacion.', specs:['Codigo 9999-7210','PD004']},
  {id:'pdm-parafil-lab-primer', code:'PD005', cat:'primadent', brand:'orthopremium', name:'Parafil LAB Primer para Metal 7ml', unit:'frasco 7ml', img:'imagenes/primadent/pag_09.jpg', desc:'Primer para metal para adherir Parafil LAB en restauraciones metalicas o de resina.', specs:['Frasco 7ml','Codigo 9999-7220','PD005']},
  {id:'pdm-parafil-lab-modeler', code:'PD006', cat:'primadent', brand:'orthopremium', name:'Parafil LAB Modeler 7ml', unit:'frasco 7ml', img:'imagenes/primadent/pag_09.jpg', desc:'Liquido modelador para dar forma y caracterizar restauraciones de Parafil LAB antes del fotocurado.', specs:['Frasco 7ml','Codigo 9999-7260','PD006']},
  {id:'pdm-parafil-gingiva', code:'PD008G', cat:'primadent', brand:'orthopremium', name:'Parafil Gingiva — Composite Gingival Fotocurable', unit:'kit / jeringa', img:'imagenes/primadent/pag_10.jpg', desc:'Composite fotopolimerizable para reproducir tonos naturales de encia. Compatible con Parafil LAB. Ideal para protesis y caracterizacion de acrilicos.', specs:['Body 4.5g: G21, G22, G23 — PD008G','Modificador 2g: GM21, GM22, GM23 — PD009GM','Opacador gingival: 9999-7100','Modificador opaco: 9999-GOM2']},
  {id:'pdm-parafil-stain', code:'PD010', cat:'primadent', brand:'orthopremium', name:'Parafil Stain — Sistema de Caracterizacion', unit:'kit 8 jeringas', img:'imagenes/primadent/pag_11.jpg', desc:'8 tonos de caracterizacion en jeringas con punta ultra fina para estructuras dentales. Compatible con Parafil LAB, Gingiva y composites fotopolimerizables.', specs:['8 colores: Beige, Azul, Cafe, Amarillo, Blanco, Naranja, Gris, Rosa','Jeringas de 1.6g — PD011 por jeringa','Kit 8 jeringas: 9999-7300 — PD010']},
  {id:'pdm-parafil', code:'PD014', cat:'primadent', brand:'orthopremium', name:'Parafil — Composite Directo Zirconio', unit:'jeringa 4.5g', img:'imagenes/primadent/pag_13.jpg', desc:'Composite fotopolimerizable directo con relleno de zirconia-silice al 60%. Resistente al desgaste, estetico y radiopaco. Para restauraciones clase I-V.', specs:['Relleno 60% en volumen (zirconia-silica)','Particula 0.04 a 2 micras','BIS-GMA, UDMA y TRI-EDMA','Codigo PD014']},
  {id:'pdm-parafil-kit20', code:'PD012', cat:'primadent', brand:'orthopremium', name:'Parafil Kit 20 Jeringas + Adhesivo', unit:'kit', img:'imagenes/primadent/pag_14.jpg', desc:'Kit completo de Parafil composite con 20 jeringas en los tonos mas populares, adhesivo fotocurable y accesorios.', specs:['20 jeringas 4.5g','Adhesivo fotocurable incluido','Codigo PD012']},
  {id:'pdm-nanohybrid', code:'PD015', cat:'primadent', brand:'orthopremium', name:'Prime-Dent Nano Hybrid Composite', unit:'jeringa 4.5g', img:'imagenes/primadent/pag_16.jpg', desc:'Resina nanohibrida con nanoclusters de 7nm. Combina fuerza de hibrido y pulido de microrelleno. Liberacion de fluor. No sensible a luz ambiente.', specs:['Relleno 74% en peso','Kit 7 jeringas: codigo 001-610','Kit 2 jeringas: codigo 001-616','Codigo PD015/PD017']},
  {id:'pdm-hybrid', code:'PD022', cat:'primadent', brand:'orthopremium', name:'Prime-Dent Hybrid Composite', unit:'kit 7 jeringas', img:'imagenes/primadent/pag_18.jpg', desc:'Resina fotocurable hibrida para restauraciones anteriores y posteriores. Alta resistencia a la compresion, radiopaco, facil manipulacion.', specs:['7 x 4.5g jeringas (A1, A2, A3, A3.5, B2, C1, U0)','Adhesivo fotocurable y acido grabador incluidos','Codigo 001-010 — PD022']},
  {id:'pdm-chemcure', code:'PD025', cat:'primadent', brand:'orthopremium', name:'Prime-Dent Chemical Cure Composite', unit:'kit', img:'imagenes/primadent/pag_18.jpg', desc:'Composite autocurable (pasta base-catalizador) para restauraciones anteriores y posteriores. Color universal, alta resistencia 270 MPa, baja absorcion de agua.', specs:['7g pasta catalizadora + 7g pasta base','3ml bonding catalizador + 3ml bonding base','3ml acido grabador liquido + accesorios','Codigo 002-005 — PD025']},
  {id:'pdm-veneer-cement', code:'Veneer-TS', cat:'primadent', brand:'orthopremium', name:'Veneer Cement Translucent Shade', unit:'jeringa', img:'imagenes/primadent/pag_21.jpg', desc:'Cemento fotocurable para cementacion de carillas dentales. Excelente estabilidad de color, 67% de relleno, facil de manejar. Apariencia similar a dientes reales.', specs:['Formulacion fotocurable','67% de relleno','Made in USA']},
  {id:'pdm-automix-cement', code:'PD027', cat:'primadent', brand:'orthopremium', name:'Automix Dual Cure Luting Cement', unit:'jeringa 10g', img:'imagenes/primadent/pag_23.jpg', desc:'Cemento dual auto-mezclable para cementacion de protesis sobre implantes, coronas, puentes, inlays, onlays, carillas, postes y pernos. Libera fluor.', specs:['Shade A2: codigo 100-101','Shade Blue: codigo 100-113','Shade White Opaque: codigo 100-121','Tiempo trabajo 2 min / Fraguado 5 min']},
  {id:'pdm-lc-glass-ionomer', code:'PD029', cat:'primadent', brand:'orthopremium', name:'Light Cure Glass Ionomer Universal Restorative', unit:'kit', img:'imagenes/primadent/pag_25.jpg', desc:'Ionomero de vidrio fotocurable con micro-particulas de vidrio. Alta liberacion de fluor. Ideal para clase III/V, erosiones cervicales, pediatrico y base/liner.', specs:['Shade A1: codigo 000184','Shade A2: codigo 000185','Shade A3: codigo 000186','Frasco 15g polvo + 6.8ml liquido']},
  {id:'pdm-zoe-cement', code:'010-080', cat:'primadent', brand:'orthopremium', name:'Zinc Oxide Eugenol Cement (ZOE)', unit:'kit', img:'imagenes/primadent/pag_28.jpg', desc:'Cemento provisional no irritante de oxido de zinc-eugenol para base y cementacion provisional de coronas y puentes. Fuerte adhesion, facil remocion.', specs:['Kit: 21g polvo + 7.5ml liquido (010-080)','Polvo refill: 010-081','Liquido refill: 010-082']},
  {id:'pdm-surgical-cement', code:'024-020', cat:'primadent', brand:'orthopremium', name:'Surgical Cement — ZOE Reforzado con Fibra', unit:'kit', img:'imagenes/primadent/pag_28.jpg', desc:'Cemento ZOE reforzado con agentes de fibra. Efecto sedante sobre la pulpa, resistencia 5400 PSI. Para cementacion donde hay tubulos dentinarios expuestos.', specs:['4 oz. polvo + 2 oz. liquido','Codigo 024-020']},
  {id:'pdm-copal-varnish', code:'010-051', cat:'primadent', brand:'orthopremium', name:'Copal Varnish & Solvent', unit:'frasco 15ml', img:'imagenes/primadent/pag_28.jpg', desc:'Barniz aislante termico y electrico. Crea fuerte union entre dentina y restauracion. Formula libre de cloroformo en barniz y sellador.', specs:['Copal Varnish 15ml: codigo 010-051','Copal Varnish Solvent 15ml: codigo 010-050']},
  {id:'pdm-self-etch', code:'PD069', cat:'primadent', brand:'orthopremium', name:'Self Etch Bonding Agent — Auto-Grabante', unit:'frasco 7ml', img:'imagenes/primadent/pag_30.jpg', desc:'Adhesivo fotopolimerizable auto-grabante todo en uno. Graba, prepara la union y desensibiliza dentina y esmalte en un solo paso.', specs:['Frasco 7ml','Codigo 006-033','PD069']},
  {id:'pdm-porcelain-repair', code:'PD070', cat:'primadent', brand:'orthopremium', name:'Porcelain Repair Kit', unit:'kit', img:'imagenes/primadent/pag_30.jpg', desc:'Kit para adherir restauraciones sobre superficies metalicas y ceramicas. Incluye Dental Dam, Porcelain Etch, Silane Bond y Drying Agent.', specs:['1.2ml Dental Dam + 1.2ml Porcelain Etch','1.2ml Silane Bond + 1.2ml Drying Agent','Agujas dispensadoras e instructivo','Codigo 008-PRK — PD070']},
  {id:'pdm-silane', code:'PD079', cat:'primadent', brand:'orthopremium', name:'Silane Porcelain Bond Enhancer', unit:'jeringa 1.2ml', img:'imagenes/primadent/pag_30.jpg', desc:'Silano de un componente para aumentar la resistencia de union de resinas organicas con composites y cementos de resina a la porcelana.', specs:['Jeringa 1.2ml con agujas dispensadoras','Codigo 008-SBE','PD079']},
  {id:'pdm-bonding-resin', code:'PD039', cat:'primadent', brand:'orthopremium', name:'Light Cure Bonding Resin — Adhesivo 5a Generacion', unit:'frasco 7ml', img:'imagenes/primadent/pag_31.jpg', desc:'Adhesivo multifuncional fotocurable de 5a generacion, hidrofilo para tecnica de union en humedo. Adhiere composites, compomeros, amalgama tratada y ceramicas.', specs:['Frasco 7ml','Codigo 006-030','PD039']},
  {id:'pdm-hema-desensitizer', code:'PD040', cat:'primadent', brand:'orthopremium', name:'Hema Desensitizer 7ml', unit:'frasco 7ml', img:'imagenes/primadent/pag_31.jpg', desc:'Desensibilizante con cloruro de benzalconio y HEMA para sellar tubulos dentinarios. Barrera de proteccion fisiologica anti-microbiana.', specs:['Frasco 7ml','Codigo 018-011','PD040']},
  {id:'pdm-prime-gel', code:'018-016', cat:'primadent', brand:'orthopremium', name:'Prime-Gel — Anestesia Topica 20% Benzocaina', unit:'frasco 1oz', img:'imagenes/primadent/pag_35.jpg', desc:'Anestesia topica en gel de benzocaina al 20%. Efecto inmediato en 5-10 minutos. Sin sabor amargo. Disponible en 8 sabores.', specs:['Pina Colada (018-014), Naranja (018-016)','Cereza (018-017), Menta (018-018)','Fresa (018-024), Raspberry (018-025)','H. Vainilla (018-026), Sandia (018-027)']},
  {id:'pdm-pit-fissure', code:'PD046', cat:'primadent', brand:'orthopremium', name:'L/C Pit and Fissure Sealant', unit:'kit 3 jeringas', img:'imagenes/primadent/pag_35.jpg', desc:'Sellador de fosetas y fisuras fotocurable. Consistencia fluida, alta fuerza de union al esmalte, resistente al desgaste. Contiene fluor. Opaco y claro.', specs:['Kit Light Cure 3x1.5g jeringas + acido: 007-022','Kit Chemical Cure botellas: 007-023','PD046']},
  {id:'pdm-prime-paste', code:'PD067', cat:'primadent', brand:'orthopremium', name:'Prime-Paste Prophylaxis Paste — Unidosis', unit:'100 copas', img:'imagenes/primadent/pag_36.jpg', desc:'Pasta profilactica con fluoruro de sodio, libre de salpicaduras. Disponible en grano medio y grueso, 6 sabores diferentes.', specs:['100 copas unidosis 100g o 200g','Grano Medio: Cereza, Menta, Pina, Chicle, Naranja, Frambuesa','Grano Grueso: Cereza, Menta','Codigo PD067']},
  {id:'pdm-root-canal', code:'022-010', cat:'primadent', brand:'orthopremium', name:'Root Canal Filling Material — Obturacion Radicular', unit:'kit', img:'imagenes/primadent/pag_37.jpg', desc:'Material libre de plata para obturacion permanente de conductos radiculares. Minima contraccion durante fraguado, excelente compatibilidad con tejidos.', specs:['Kit polvo 8g + resina 10g + accesorios: 022-010','Polvo 8g refill: 022-011 / Resina 10g: 022-012','PD058']},
  {id:'pdm-rc-cream', code:'PD049', cat:'primadent', brand:'orthopremium', name:'RC-Cream — Preparacion Quimico-Mecanica Conductos', unit:'jeringas', img:'imagenes/primadent/pag_37.jpg', desc:'Quelante viscoso de glicol, peroxido de urea y EDTA para preparacion de conductos radiculares calcificados. Limpieza rapida y mayor penetracion del instrumental.', specs:['Kit 32 x 9g jeringas: 022-050','Kit 2 x 9g jeringas: 022-054','Refill 9g jeringa: 022-052','Codigo PD049']},
  {id:'pdm-tray-adhesive', code:'017-019', cat:'primadent', brand:'orthopremium', name:'Tray Adhesive — Adhesivo para Cubeta', unit:'frasco 1oz', img:'imagenes/primadent/pag_39.jpg', desc:'Adhesivo para cubeta de alginato. Mantiene el alginato fijo en la cubeta al retirarla de la boca. Incluye cepillo con tapa.', specs:['Ambar: codigo 017-019','Azul: codigo 017-020']},
  {id:'pdm-dental-dam', code:'PD050', cat:'primadent', brand:'orthopremium', name:'Dental Dam — Barrera Gingival Fotocurable', unit:'kit 4 jeringas', img:'imagenes/primadent/pag_39.jpg', desc:'Resina fotocurable de baja viscosidad para proteccion de tejidos blandos durante blanqueamiento. Facil aplicacion y remocion en una sola pieza.', specs:['Kit 4 x 3.5g jeringas + 20 dispersadores (021-011)','Refill 3.5g jeringa c/5 dispersadores (021-010)','Codigo PD050']},
  {id:'pdm-block-out-resin', code:'PD051', cat:'primadent', brand:'orthopremium', name:'Block Out Resin — Resina de Bloqueo Fotocurable', unit:'kit', img:'imagenes/primadent/pag_39.jpg', desc:'Resina fotocurable pigmentada para reparacion de modelos de impresion y creacion de depositos de blanqueamiento en acetatos.', specs:['Kit 4 x 3.5g jeringas + 20 dispersadores (021-021)','Refill 33.5g o 2g jeringa','Codigo PD051']},
  {id:'pdm-prime-core', code:'PD053', cat:'primadent', brand:'orthopremium', name:'Prime-Core DC — Material de Munon Doble Curado', unit:'kit jeringas Automix', img:'imagenes/primadent/pag_40.jpg', desc:'Material de reconstruccion de munones (core build-up) de doble curado auto-mezclable. Libera fluor, altamente radiopaco. Colores A2 y Azul.', specs:['Kit 4 x 10g jeringas A2 + puntas (003-080)','Kit 4 x 10g jeringas Blue + puntas (003-083)','Jeringa 10g A2 (003-082) / Blue (003-085)','Codigo PD053']},
  {id:'pdm-ortho-adhesive-lc', code:'PD056', cat:'ortodoncia', brand:'orthopremium', name:'Light Cure Orthodontic Adhesive Bonding System', unit:'kit 1 jeringa', img:'imagenes/primadent/pag_42.jpg', desc:'Sistema adhesivo fotopolimerizable para brackets de plastico, metal o porcelana. Fotocura en 30 seg. Alta viscosidad para posicionamiento preciso. Libera fluor.', specs:['5g jeringa + 3ml adhesivo + 3ml acido grabador','Codigo 012-021','Codigo PD056']},
  {id:'pdm-ortho-adhesive-sc', code:'PD058-OA', cat:'ortodoncia', brand:'orthopremium', name:'One-Step Orthodontic Adhesive — Chemical Cure', unit:'kit 1 jeringa', img:'imagenes/primadent/pag_43.jpg', desc:'Sistema adhesivo autocurable (catalizador/base) para brackets de plastico, metal o porcelana. Maxima dureza en 5 minutos. Alta viscosidad.', specs:['5g jeringa + 5ml primer + 3ml acido grabador','Codigo 011-019','Codigo PD058']},
  {id:'pdm-band-cement', code:'PD059', cat:'ortodoncia', brand:'orthopremium', name:'Dual Cure Glass Ionomer Band Cement', unit:'kit jeringa Automix', img:'imagenes/primadent/pag_43.jpg', desc:'Cemento dual de ionomero de vidrio y resina para cementacion de bandas metalicas. Libera fluor, alta resistencia, fotopolimerizable para acelerar.', specs:['10g jeringa A2 + 5 puntas mezcladoras + 5 puntas intraorales','Codigo 015-028','Codigo PD059']},
  {id:'pdm-mixing-pads', code:'mp-3x5', cat:'primadent', brand:'orthopremium', name:'Mixing Pads — Blocs de Papel para Mezcla', unit:'bloc', img:'imagenes/primadent/pag_44.jpg', desc:'Papel encerado que impide la absorcion del material en la superficie. Disponible en 4 tamaños.', specs:['2x2" (mp-2x2)','3x3" (mp-3x3)','3x5" (mp-3x5)','5x7" (mp-5x7)']},
  {id:'pdm-mixing-spatulas', code:'030-001', cat:'primadent', brand:'orthopremium', name:'Mixing Spatulas — Espatulas Desechables', unit:'bolsa 100 pzas', img:'imagenes/primadent/pag_44.jpg', desc:'Espatulas desechables de plastico para mezcla de pastas dentales. Presentacion de 50 o 100 piezas.', specs:['100 pzas: codigo 030-001','50 pzas: codigo 030-003']},
  {id:'pdm-brushes', code:'030-010', cat:'primadent', brand:'orthopremium', name:'Brushes and Holder — Cepillos Aplicadores', unit:'bolsa', img:'imagenes/primadent/pag_44.jpg', desc:'Cepillos desechables para aplicacion de resinas y liquidos. Cortos (7/8") y largos (2"). Incluye portacepillos.', specs:['Portacepillos: codigo 030-026','Cepillos cortos 50/bolsa: 030-010','Cepillos 2" largos 50/bolsa: 030-020']},
  {id:'pdm-needle-tips', code:'030-024', cat:'primadent', brand:'orthopremium', name:'Luer Lock Needle Tips — Agujas Dispensadoras', unit:'caja 100 pzas', img:'imagenes/primadent/pag_44.jpg', desc:'Agujas dispensadoras Luer lock para todos los tamaños de jeringas dentales. Calibres 18G, 20G, 22G y 24G.', specs:['Black 20 Gauge 100/caja (030-024)','Black 18 Gauge 100/caja (030-025)','Grey 22 Gauge 100/caja (030-026)','Blue 24 Gauge 100/caja (030-027)']},
  {id:'pdm-top-sticks', code:'OP3200', cat:'ortodoncia', brand:'orthopremium', name:'Top-Sticks — Modulos Elasticos Ortodoncia', unit:'pack', img:'imagenes/primadent/pag_45.jpg', desc:'Modulos elasticos de poliuretano de calidad medica. Alta elasticidad, libre de latex. Mas de 50 colores disponibles.', specs:['42 stick pack / 24 ring stick / 1008 rings pack','Codigo OP3200','Mas de 50 colores: Clear, White, Black y todos los colores']},
  {id:'pdm-top-chain', code:'OP3210', cat:'ortodoncia', brand:'orthopremium', name:'Top-Chain — Cadena Elastica Ortodoncia', unit:'carrete 4.5m', img:'imagenes/primadent/pag_46.jpg', desc:'Cadena elastica de poliuretano medico libre de latex. Alta elasticidad y rebote. 3 tamaños y mas de 50 colores.', specs:['Continuo 2.8mm (OP3210) / Corto 3.5mm (OP3220) / Largo 4.2mm (OP3230)','Carrete de 4.5m','Mas de 50 colores disponibles']},
"""

# 4. New Balsas products (Zhermack + extras not yet in DB)
balsas_block = """\
  {id:'balsas-018', code:'C300200', cat:'materiales', brand:'balsas', name:'Indurent Gel — Catalizador para Siliconas-C', unit:'tubo', img:'imagenes/balsas/pag_30.jpg', desc:'Catalizador en gel de color rojo para siliconas por condensacion (Zetaplus y Oranwash L). Visualiza la mezcla homogenea, versatil para todas las tecnicas de impresion.', specs:['Dosificar en partes iguales con Oranwash L','Compatible con Zetaplus y Zetalabor']},
  {id:'balsas-019', code:'C500100', cat:'instrumental', brand:'balsas', name:'Hi-Tray Metal — Portaimpresion Metalica', unit:'par', img:'imagenes/balsas/pag_32.jpg', desc:'Cubeta de acero inoxidable especial BSA con 16.70% de cromo y bordes retentivos. Esterilizable en seco y en autoclave. Sistema Rim Lock para adhesion del material.', specs:['Alta resistencia a la deformacion','Mayor exactitud de la impresion','Disponible: Solido y Perforado','Superior e Inferior']},
  {id:'balsas-020', code:'C500200', cat:'instrumental', brand:'balsas', name:'Hi-Tray Light Clear — Portaimpresion Plastica', unit:'pieza', img:'imagenes/balsas/pag_32.jpg', desc:'Cubeta estandar de plastico transparente extra rigido. Esterilizable en autoclave. Disponible en varias medidas y formas.', specs:['Small/Medium/Large superior e inferior','Parcial superior derecho e izquierdo','Rigida para evitar distorsiones']},
  {id:'balsas-021', code:'Z7ULTRA', cat:'materiales', brand:'balsas', name:'Zeta 1 Ultra — Desinfectante Concentrado', unit:'frasco', img:'imagenes/balsas/pag_34.jpg', desc:'Desinfectante y detergente concentrado sin aldehidos de accion completa para instrumentos odontologicos. 1 litro rinde para 100 litros de solucion.', specs:['Frasco 125 ml o Botella 1 litro','Dilución: 1%','Bactericida, Fungicida, Microbactericida','Incluido tuberculicida, virucida (HIV, HBV, HCV, H1N1, H5N1)']},
  {id:'balsas-022', code:'Z2SPOREX', cat:'materiales', brand:'balsas', name:'Zeta 2 Sporex — Desinfectante Esterilizador en Polvo', unit:'bote 900g', img:'imagenes/balsas/pag_34.jpg', desc:'Desinfectante y esterilizador en polvo de accion completa para instrumentos de goma, plastico, endoscopios y fibras opticas no autoclavables.', specs:['Bote 900g con medidor','Dilución 2% — 45 litros de solucion','Bactericida, Fungicida, Esporicida','Virucida (HIV, HBV, HCV, H1N1, H5N1)']},
  {id:'balsas-023', code:'ZETACLAVE', cat:'equipos', brand:'balsas', name:'Zetaclave B — Autoclave Clase B Zhermack', unit:'equipo', img:'imagenes/balsas/pag_39.jpg', desc:'Autoclave Clase B con vacio fraccionado. Camara de acero inoxidable 18 litros, display grafico LCD, 12 programas preconfigurados, impresora termica integrada.', specs:['Camara: 236x381mm, 18 litros','Dimensiones: 450x615x400mm, 45 kg','Tension: 220-240V, 2400W','Tres ciclos convalidados: Helix, Bowie & Dick Vacuum']},
  {id:'balsas-024', code:'C700100', cat:'materiales', brand:'balsas', name:'Elite Model — Yeso Tipo 3 para Modelos', unit:'saco 3kg', img:'imagenes/balsas/pag_55.jpg', desc:'Yeso tipo 3 para modelos en general y antagonistas. Realizacion de modelos de estudio, antagonistas y muflas en protesis removibles. Baja expansion, alta resistencia.', specs:['Relacion agua/polvo: 30ml/100g','Expansion 48h: 0.07%','Resistencia a la compresion: 62 MPa a 48h','Colores: Steel Blue, Ivory, White']},
  {id:'balsas-025', code:'C700110', cat:'materiales', brand:'balsas', name:'Elite Model Fast — Yeso Tipo 3 Rapido', unit:'saco 3kg', img:'imagenes/balsas/pag_55.jpg', desc:'Yeso rapido tipo 3 para modelos en general. Tiempo de fraguado 8 minutos. Tixotropico, fluido ideal bajo vibracion, extrema versatilidad. Alta resistencia.', specs:['Relacion agua/polvo: 30ml/100g','Expansion 48h: 0.1%','Resistencia a la compresion: 65 MPa a 48h','Colores: Light Cream, White']},
"""

# 5. Check which new IDs already exist and build clean blocks
def filter_block(block_text):
    entries = re.findall(r"\{id:'[^']+'.+?\}", block_text, re.DOTALL)
    result = ""
    added = 0
    for entry in entries:
        m = re.search(r"id:'([^']+)'", entry)
        if m and m.group(1) not in existing_ids:
            result += "  " + entry.strip() + ",\n"
            added += 1
    return result, added

pdm_clean, pdm_count = filter_block(primadent_block)
balsas_clean, balsas_count = filter_block(balsas_block)

print(f"Primadent nuevos: {pdm_count}")
print(f"Balsas nuevos: {balsas_count}")

# 6. Insert all before closing '];'
new_section = ""
if vamasa_block:
    new_section += "\n  // ===== VAMASA / Ultradent nuevos productos =====\n" + vamasa_block
if pdm_clean:
    new_section += "\n  // ===== Prime Dental Manufacturing (Primadent) =====\n" + pdm_clean
if balsas_clean:
    new_section += "\n  // ===== Balsas Dental / Zhermack nuevos =====\n" + balsas_clean

idx = content.rfind('];')
content = content[:idx].rstrip() + new_section + '\n];\n'

total = len(re.findall(r"id:'[a-zA-Z0-9_-]+'", content))
print(f"Total productos: {total}")

with open(r'C:\Catalago Prodent\website\js\products-data.js', 'w', encoding='utf-8') as f:
    f.write(content)
print("GUARDADO")
