// ============================================================
// NUEVOS PRODUCTOS VAMASA (Ultradent) — extraídos del catálogo
// Páginas escaneadas: pag_01.jpg a pag_60.jpg
// Productos ya existentes (vamasa-001 a vamasa-023) omitidos.
// Iniciar desde vamasa-024
// ============================================================

// --- BLANQUEAMIENTO (pag_02) ---
{id:'vamasa-024', code:'01-0401', cat:'materiales', brand:'vamasa', name:'Pasta dental Opalescence', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Pasta de mantenimiento diario para blanqueamiento dental.', specs:['Mantenimiento diario','Presentación 12 pastas 4.7 oz o 24 pastas 1 oz']},
{id:'vamasa-025', code:'01-05551', cat:'materiales', brand:'vamasa', name:'Opalustre', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Pasta de abrasión química y mecánica para eliminar manchas del esmalte.', specs:['Presentación jeringas de 1.2 ml','Uso con Opal Cups']},
{id:'vamasa-026', code:'01-1323', cat:'materiales', brand:'vamasa', name:'Opalescence Endo al 35%', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Blanqueador dental interno para dientes endodónticamente tratados.', specs:['Concentración 35%','2 jeringas de 1.2 ml sin puntas']},
{id:'vamasa-027', code:'01-1008', cat:'materiales', brand:'vamasa', name:'UltraEz', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Desensibilizante dental al 3% para uso previo o posterior al blanqueamiento.', specs:['Concentración 3%','Presentaciones: 4, 20 y combo 10 cucharillas']},
{id:'vamasa-028', code:'01-5346', cat:'materiales', brand:'vamasa', name:'Opalescence Quick 45%', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Blanqueamiento dental de alta concentración para sala de espera.', specs:['Concentración 45%','4 jeringas c/4 puntas o 20 jeringas c/20 puntas']},
{id:'vamasa-029', code:'01-0242', cat:'materiales', brand:'vamasa', name:'Resina LC Block Out', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Resina bloqueadora fotocurable para uso extra-oral en elaboración de guardas.', specs:['20 jeringas de 1.2 ml c/20 puntas','2 jeringas de 1.2 ml c/10 puntas']},
{id:'vamasa-030', code:'01-4870', cat:'desechables', brand:'vamasa', name:'Umbrella', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Retractor de tejido blando desechable para mayor visibilidad durante procedimientos.', specs:['Retractor Umbrella 5 pzs','Retractor Umbrella 40 pzs']},
{id:'vamasa-031', code:'01-0331', cat:'desechables', brand:'vamasa', name:'Iso Block', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Retractor de lengua desechable para aislamiento en procedimientos dentales.', specs:['Con 10 pzs']},
{id:'vamasa-032', code:'01-0604', cat:'instrumental', brand:'vamasa', name:'Vinyl Cutters', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Tijeras para confección de guardas de blanqueamiento en vinilo.', specs:['1 pieza']},
{id:'vamasa-033', code:'01-0605', cat:'instrumental', brand:'vamasa', name:'UltraTrim', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Tijeras de precisión para recorte de guardas suaves de blanqueamiento.', specs:['1 pieza']},
{id:'vamasa-034', code:'01-1820', cat:'desechables', brand:'vamasa', name:'KleerView', unit:'unidad', img:'imagenes/vamasa/pag_02.jpg', desc:'Retractor de labios y mejillas desechable para máxima visibilidad.', specs:['Tamaño Infantil','Tamaño Adulto']},

// --- PREVENCIÓN / MANEJO DE TEJIDOS (pag_03) ---
{id:'vamasa-035', code:'01-8318', cat:'desechables', brand:'vamasa', name:'Ultrapro Tx', unit:'unidad', img:'imagenes/vamasa/pag_03.jpg', desc:'Contrangulo profiláctico desechable para profilaxis dental.', specs:['Contrangulo Suave-Verde c/500 pzs','Contrangulo Dura-Azul c/500 pzs']},
{id:'vamasa-036', code:'01-1805', cat:'materiales', brand:'vamasa', name:'Sable Seek', unit:'unidad', img:'imagenes/vamasa/pag_03.jpg', desc:'Indicador de caries para detección de tejido cariado durante la preparación.', specs:['20 jeringas de 1.2 ml sin puntas','4 jeringas de 1.2 ml sin puntas']},
{id:'vamasa-037', code:'01-0226', cat:'materiales', brand:'vamasa', name:'Láminas SoftTray', unit:'unidad', img:'imagenes/vamasa/pag_03.jpg', desc:'Guarda suave para blanqueamiento nocturno y protección dental.', specs:['25 láminas de 5" x 5" al .035"']},
{id:'vamasa-038', code:'01-4100', cat:'desechables', brand:'vamasa', name:'PropGard', unit:'unidad', img:'imagenes/vamasa/pag_03.jpg', desc:'Abrebocas y retenedor de lengua para aislamiento durante procedimientos.', specs:['5 Grandes Amarillas / 5 Normales Purpura','20 Protectores de lingüales (10 lrg y 10 der.)']},
{id:'vamasa-039', code:'01-3097', cat:'desechables', brand:'vamasa', name:'InterGuard', unit:'unidad', img:'imagenes/vamasa/pag_03.jpg', desc:'Protector de diente adyacente durante procedimientos de grabado y adhesión.', specs:['5 de c/tamaño 4 y 5.5 mm','50 Interguard de 4 mm o 5.5 mm']},
{id:'vamasa-040', code:'01-0732', cat:'materiales', brand:'vamasa', name:'Consepsis Scrub', unit:'unidad', img:'imagenes/vamasa/pag_03.jpg', desc:'Pasta antibacteriana con clorhexidina al 2% para frotado del campo operatorio.', specs:['4 jeringas de 1.2 ml']},
{id:'vamasa-041', code:'01-0317', cat:'instrumental', brand:'vamasa', name:'Omni-Matrix Sectional', unit:'unidad', img:'imagenes/vamasa/pag_03.jpg', desc:'Sistema de matrices parciales y clamps de retención para restauraciones posteriores.', specs:['4 Clamps para matrices anatómicas #1','40 Matrices regulares #2, extendidas, de cría y 4 clamps']},
{id:'vamasa-042', code:'01-2352', cat:'materiales', brand:'vamasa', name:'OraSeal', unit:'unidad', img:'imagenes/vamasa/pag_03.jpg', desc:'Sellador de dique de goma fotocurable para asegurar el aislamiento.', specs:['Jeringa caulking 1.2 ml + jeringa putty 1.2 ml','Jeringas jumbo de 30 ml']},
{id:'vamasa-043', code:'01-0112', cat:'materiales', brand:'vamasa', name:'Astringedent X', unit:'unidad', img:'imagenes/vamasa/pag_03.jpg', desc:'Solución de sulfato férrico al 12.7% y subsulfato férrico de difícil sangrado.', specs:['Frasco de 30 ml']},
{id:'vamasa-044', code:'01-1094', cat:'desechables', brand:'vamasa', name:'Starbrush', unit:'unidad', img:'imagenes/vamasa/pag_03.jpg', desc:'Cepillos intraorales para aplicación de materiales en áreas de difícil acceso.', specs:['10, 30, 50 y 100 pzs']},

// --- MANEJO DE TEJIDOS / TERMINACIÓN / ADHESIÓN (pag_04) ---
{id:'vamasa-045', code:'01-0170', cat:'instrumental', brand:'vamasa', name:'Empacador de hilo retractor', unit:'unidad', img:'imagenes/vamasa/pag_04.jpg', desc:'Instrumentos para empacado de hilo retractor de tejido gingival.', specs:['Empacador normal 45°, pequeño 45°, normal 90° y pequeño 90°','Empacador regular y chico (NO dentados)']},
{id:'vamasa-046', code:'01-0131', cat:'materiales', brand:'vamasa', name:'Hilos UltraPak', unit:'unidad', img:'imagenes/vamasa/pag_04.jpg', desc:'Hilos para retracción de tejidos gingivales de 244 cm, en múltiples calibres.', specs:['Hilo #0 Morado, #1 Azul, #2 Verde, #3 Rojo, #00 Amarillo, #000 Negro','Estuche Ultrapak incluye organizador']},
{id:'vamasa-047', code:'01-0406', cat:'materiales', brand:'vamasa', name:'Porcelain Etch y Silano', unit:'unidad', img:'imagenes/vamasa/pag_04.jpg', desc:'Grabador y silano para porcelanas en procedimientos de cementación adhesiva.', specs:['2 jeringas de 1.2 ml Porcelain Etch','2 jeringas de 1.2 ml Silano','Kit combinado disponible']},
{id:'vamasa-048', code:'01-6409', cat:'materiales', brand:'vamasa', name:'ViscoStat Clear', unit:'unidad', img:'imagenes/vamasa/pag_04.jpg', desc:'Hemostático de cloruro de aluminio al 25% transparente para control de sangrado.', specs:['4 jeringas de 1.2 ml y 20 puntas','20 jeringas de 1.2 ml','Jeringa jumbo de 30 ml']},
{id:'vamasa-049', code:'01-1029', cat:'instrumental', brand:'vamasa', name:'Cepillos Jiffy', unit:'unidad', img:'imagenes/vamasa/pag_04.jpg', desc:'Cepillos de pelo de cabra y copa para pulido y acabado de restauraciones.', specs:['Disco pelo de cabra c/10 pzs','Cepillo copa regular c/5 y 10 pzs','Cepillo de punta c/5 y 10 pzs']},
{id:'vamasa-050', code:'01-4018', cat:'materiales', brand:'vamasa', name:'Kits Jiffy Universal', unit:'unidad', img:'imagenes/vamasa/pag_04.jpg', desc:'Kit de ajuste y pulido universal para porcelana, intra-oral y extra-oral.', specs:['Kit de ajuste y pulido Universal Extra-Oral','Kit de ajuste y pulido Universal Intra-Oral']},

// --- TERMINACIÓN / RESTAURACIÓN (pag_05) ---
{id:'vamasa-051', code:'01-1722', cat:'materiales', brand:'vamasa', name:'Jiffy Polishing Kit', unit:'unidad', img:'imagenes/vamasa/pag_05.jpg', desc:'Estuche de pulido con copas, puntas, disco y fresa para acabado de compósitos.', specs:['3 copas, 3 puntas, 1 disco y 1 fresa']},
{id:'vamasa-052', code:'01-1723', cat:'materiales', brand:'vamasa', name:'EZ Jiffy Polishing Kit', unit:'unidad', img:'imagenes/vamasa/pag_05.jpg', desc:'Estuche de pulidores y cepillos para terminación de compósitos y cerámica.', specs:['1 cepillo copa regular, 1 cepillo de punta','3 copas, 3 puntas y 3 discos']},
{id:'vamasa-053', code:'01-0238', cat:'materiales', brand:'vamasa', name:'DeOx', unit:'unidad', img:'imagenes/vamasa/pag_05.jpg', desc:'Barrera contra el oxígeno en solución viscosa para inhibición de la capa superficial.', specs:['4 jeringas de 1.2 ml repuesto','2 jeringas de 1.2 ml c/10 puntas']},
{id:'vamasa-054', code:'01-1166', cat:'instrumental', brand:'vamasa', name:'Sierra proximal Jiffy', unit:'unidad', img:'imagenes/vamasa/pag_05.jpg', desc:'Sierra proximal para separación de contactos y terminación interdental.', specs:['12 sierras de 8 mm']},
{id:'vamasa-055', code:'01-1162', cat:'materiales', brand:'vamasa', name:'Tiras diamantadas Jiffy', unit:'unidad', img:'imagenes/vamasa/pag_05.jpg', desc:'Tiras de acero inoxidable con diamante para terminación y contorneado proximal.', specs:['10 tiras regulares 3.75 mm','10 tiras finas 2.5 mm','Presentaciones delgada, mediano y extra fino 2.5 mm, grueso 4 mm']},

// --- RESTAURACIÓN (pag_05) — Resina Forma ya existe como vamasa-016 ---

// --- LÁMPARAS DE FOTOCURADO (pag_06 / pag_07) ---
{id:'vamasa-056', code:'01-5934', cat:'equipos', brand:'vamasa', name:'Lentes protectores UltraTect', unit:'unidad', img:'imagenes/vamasa/pag_06.jpg', desc:'Lentes protectores contra la luz de fotocurado en tres presentaciones de color.', specs:['Marrón (01-0914)','Transparentes (01-0501)','Naranja UV (01-0508)']},
{id:'vamasa-057', code:'01-5941', cat:'equipos', brand:'vamasa', name:'VALO Cordless', unit:'unidad', img:'imagenes/vamasa/pag_07.jpg', desc:'Lámpara de fotocurado LED inalámbrica VALO con batería recargable y colores a pedido.', specs:['Código 01-5941','Accesorios: cargador, pilas, cable, 500 barreras protectoras']},
{id:'vamasa-058', code:'01-5972', cat:'equipos', brand:'vamasa', name:'VALO Grand', unit:'unidad', img:'imagenes/vamasa/pag_07.jpg', desc:'Lámpara de fotocurado LED VALO Grand con huella extra grande que cura un molar en un solo disparo.', specs:['4 baterías recargables','Cargador de baterías','Fuente de alimentación','Pantalla protectora con filtro UV']},

// --- ENDODONCIA (pag_08) ---
{id:'vamasa-059', code:'01-0963', cat:'materiales', brand:'vamasa', name:'PermaFlo Pink', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Composite fluido fotocurable de color rosa para restauraciones estéticas.', specs:['2 jeringas de 1.2 ml']},
{id:'vamasa-060', code:'01-0962', cat:'materiales', brand:'vamasa', name:'PermaFlo Purple', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Composite fluido fotocurable de color púrpura para restauraciones pediátricas.', specs:['2 jeringas de 1.2 ml']},
{id:'vamasa-061', code:'01-5912', cat:'materiales', brand:'vamasa', name:'PermaFlo DC', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Cemento dual para restauraciones cerámicas y composites de flujo automezclable.', specs:['Jeringa A2 de 5 ml y 20 puntas','Translúcido jeringa de 5 ml y 20 puntas']},
{id:'vamasa-062', code:'01-5804', cat:'materiales', brand:'vamasa', name:'EndoREZ', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Sellador de conductos radiculares a base de resina de curado dual.', specs:['Endo-Rez mini kit obturación','Jeringa Endo-Rez 3ml, 12 puntas NaviTips, 10 jeringas Skini']},
{id:'vamasa-063', code:'01-3059', cat:'materiales', brand:'vamasa', name:'Composite Wetting Resin', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Resina humectante para mejorar la fluidez y el manejo de compósitos.', specs:['2 jeringas de 1.2 ml']},
{id:'vamasa-064', code:'01-0329', cat:'materiales', brand:'vamasa', name:'Ácido cítrico al 20%', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Irrigador del conducto radicular óptimo para disolución de residuos de hidróxido de calcio.', specs:['Jeringa Jumbo de 30 ml']},
{id:'vamasa-065', code:'01-1022', cat:'materiales', brand:'vamasa', name:'File-Eze', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Quelante viscoso para facilitar la instrumentación endodóntica en conductos calcificados.', specs:['2 jeringas de 1.2 ml y 10 puntas','Jeringa Jumbo de 30 ml']},
{id:'vamasa-066', code:'01-2210', cat:'materiales', brand:'vamasa', name:'Consepsis V', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Solución viscosa antibacteriana de clorhexidina al 2% para aplicación intraconducto.', specs:['Jeringa Jumbo de 30 ml']},
{id:'vamasa-067', code:'01-0162', cat:'materiales', brand:'vamasa', name:'Solución EDTA al 18%', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Irrigador del conducto radicular para quelación y eliminación del barro dentinario.', specs:['Jeringa Jumbo de 30 ml']},
{id:'vamasa-068', code:'01-1433', cat:'desechables', brand:'vamasa', name:'Puntas Black Mini', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Puntas desechables compatibles con Ultra-Blend Plus, PermaFlo, TriAway y otros materiales.', specs:['500 pzs','100 pzs','20 pzs']},
{id:'vamasa-069', code:'01-1033', cat:'desechables', brand:'vamasa', name:'Puntas Inspiral Brush', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Puntas en espiral para aplicación de Ultra-Etch, PQ1, UltraSeal y materiales fluidos.', specs:['500 pzs','100 pzs','20 pzs']},
{id:'vamasa-070', code:'01-1168', cat:'desechables', brand:'vamasa', name:'Puntas Micro Calibre 20', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Puntas de micro calibre 20 para uso con PermaFlo, PermaFlo Purple y OpalDam.', specs:['20 pzs','100 pzs','500 pzs']},
{id:'vamasa-071', code:'01-0345', cat:'desechables', brand:'vamasa', name:'Puntas Endo-Eze', unit:'unidad', img:'imagenes/vamasa/pag_08.jpg', desc:'Puntas de irrigación endodóntica calibre 18ga a 31ga para irrigación de conductos.', specs:['18ga, 19ga, 20ga, 22ga y 30ga disponibles','20 pzs por caja']},

// --- PUNTAS Y JERINGAS (pag_09) ---
{id:'vamasa-072', code:'01-1240', cat:'desechables', brand:'vamasa', name:'Puntas NanoTip', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Puntas ultrafinas para uso con UltraSeal XT Plus, Ultra-Etch y PermaFlo.', specs:['20 pzs','100 pzs']},
{id:'vamasa-073', code:'01-0297', cat:'desechables', brand:'vamasa', name:'Puntas irrigadoras Endo-Eze', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Puntas irrigadoras para uso con ChlorCid, ChlorCid V y jeringas Ultradent de 5 ml.', specs:['20 pzs']},
{id:'vamasa-074', code:'01-1440', cat:'desechables', brand:'vamasa', name:'Puntas Blue Mini Dento-Infusor', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Puntas azules para uso con ViscoStat, Astringedent, UltraCid y Consepsis.', specs:['500 pzs','100 pzs','20 pzs']},
{id:'vamasa-075', code:'01-5121', cat:'desechables', brand:'vamasa', name:'NaviTip 31ga Irrigadora', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Punta irrigadora doble puerto 31ga para Solución EDTA, ChlorCid y Consepsis.', specs:['20 pzs 21mm','50 pzs 21mm','20 pzs 27mm']},
{id:'vamasa-076', code:'01-5112', cat:'desechables', brand:'vamasa', name:'Puntas NaviTip', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Puntas de irrigación intracanal 30 y 29 calibre para endodoncia y endodoncia.', specs:['Calibres 30 y 29','Presentaciones de 20 y 50 pzs']},
{id:'vamasa-077', code:'01-0122', cat:'desechables', brand:'vamasa', name:'Puntas Dento-Infusor', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Puntas para uso con ViscoStat Clear, Astringedent X y jeringas de 1.2 ml.', specs:['20 pzs','500 pzs']},
{id:'vamasa-078', code:'01-1452', cat:'desechables', brand:'vamasa', name:'Puntas NaviTip FX', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Puntas de doble lumen para uso con Solución Ácido cítrico al 20%.', specs:['20 pzs de 17mm','20 pzs de 25mm']},
{id:'vamasa-079', code:'01-0341', cat:'desechables', brand:'vamasa', name:'Puntas Capillary', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Puntas capilares para adaptadores de succión Luer en jeringas de 1.2 o 3 ml.', specs:['20 pzs de 0.014"','50 pzs de 0.014" o 0.019"']},
{id:'vamasa-080', code:'01-1120', cat:'desechables', brand:'vamasa', name:'Puntas Micro Capillary', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Puntas micro capilares para ultracare, endodoncia y evacuación con adaptador Luer.', specs:['20 pzs de 5 mm','100 pzs de 10 mm']},
{id:'vamasa-081', code:'01-1248', cat:'desechables', brand:'vamasa', name:'Puntas SurgiTip', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Puntas de succión Luer para periodoncia y endodoncia, y control de succión en Boost.', specs:['20 pzs']},
{id:'vamasa-082', code:'01-5920', cat:'desechables', brand:'vamasa', name:'Puntas Mezcladoras Mixing Tips', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Puntas mezcladoras desechables para UltraTemp, EndoRez y PermaFlo DC.', specs:['20 pzs mezcladoras','20 pzs intraoral']},
{id:'vamasa-083', code:'01-1595', cat:'desechables', brand:'vamasa', name:'Jeringa Skini', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Jeringa Skini desechable para uso con EndoRez y PermaFlo DC.', specs:['10 pzs','20 pzs','50 pzs']},
{id:'vamasa-084', code:'01-0205', cat:'desechables', brand:'vamasa', name:'Tapas Luer lock', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Tapas Luer lock para todas las jeringas plásticas de Ultradent.', specs:['Caja de 20 pzs']},
{id:'vamasa-085', code:'01-1375', cat:'desechables', brand:'vamasa', name:'Adaptador TriAway', unit:'unidad', img:'imagenes/vamasa/pag_09.jpg', desc:'Irrigador descartable para controlar la succión en el sistema de irrigación durante Boost.', specs:['20 pzs']},

// --- PUNTAS Y JERINGAS (pag_10) ---
{id:'vamasa-086', code:'01-1490', cat:'desechables', brand:'vamasa', name:'Puntas Micro Calibre 20 FX', unit:'unidad', img:'imagenes/vamasa/pag_10.jpg', desc:'Puntas micro calibre 20 FX para uso con Opalescence Boost.', specs:['20 pzs','100 pzs','500 pzs']},
{id:'vamasa-087', code:'01-0194', cat:'desechables', brand:'vamasa', name:'Puntas Black Micro y Blue Micro', unit:'unidad', img:'imagenes/vamasa/pag_10.jpg', desc:'Puntas Black Micro y Blue Micro para Ultra-Blend Plus, OpalDam, UltraSeal XT y Ultra-Etch.', specs:['Black Micro: 20, 100 y 500 pzs','Blue Micro: 20, 100 y 500 pzs']},
{id:'vamasa-088', code:'01-1356', cat:'desechables', brand:'vamasa', name:'Puntas Black Micro FX', unit:'unidad', img:'imagenes/vamasa/pag_10.jpg', desc:'Puntas Black Micro FX de ultra precisión para uso con Opalescence Boost.', specs:['20 pzs','100 pzs','500 pzs']},
{id:'vamasa-089', code:'01-0193', cat:'desechables', brand:'vamasa', name:'Puntas Black Mini Brush', unit:'unidad', img:'imagenes/vamasa/pag_10.jpg', desc:'Puntas brush para Consepsis, Peak SE, PermaFlo DC, Primers, PermaQuick, PermaSeal y otros.', specs:['20 pzs','100 pzs','500 pzs']},
{id:'vamasa-090', code:'01-5799', cat:'desechables', brand:'vamasa', name:'Opal Cups', unit:'unidad', img:'imagenes/vamasa/pag_10.jpg', desc:'Copas de caucho para uso con Opalustre en pulido y eliminación de manchas.', specs:['Copas de acabado 20 pzs','Copas de abrasión 20 pzs']},
{id:'vamasa-091', code:'01-0124', cat:'desechables', brand:'vamasa', name:'Jeringas Plásticas', unit:'unidad', img:'imagenes/vamasa/pag_10.jpg', desc:'Jeringas plásticas para uso intraoral de contornos y extremos redondeados Luer lock.', specs:['De 1.2 ml c/20 pzs','De 1.2 ml c/100 pzs','De 5 ml c/10 pzs']},
{id:'vamasa-092', code:'01-0249', cat:'desechables', brand:'vamasa', name:'Protectores para jeringa', unit:'unidad', img:'imagenes/vamasa/pag_10.jpg', desc:'Protectores para todas las jeringas de 1.2 ml de Ultradent para evitar que se salga la punta.', specs:['250 pzs']},
{id:'vamasa-093', code:'01-0661', cat:'desechables', brand:'vamasa', name:'Puntas White Mac y White Mini Láser', unit:'unidad', img:'imagenes/vamasa/pag_10.jpg', desc:'Puntas blancas para OraSeal Caulking, Putty, Consepsis Scrub y Opalustre.', specs:['20 White Mac','20 White Mini','100 White Mac']},
{id:'vamasa-094', code:'01-0230', cat:'desechables', brand:'vamasa', name:'Adaptador de succión Luer', unit:'unidad', img:'imagenes/vamasa/pag_10.jpg', desc:'Adaptador Luer que se adapta a cualquier sistema de succión odontológico.', specs:['10 adaptadores de succión']},

// --- SUTURAS / RIBBOND (pag_27) ---
{id:'vamasa-095', code:'47-SUGS0111', cat:'materiales', brand:'vamasa', name:'Sutura Surgeasy', unit:'unidad', img:'imagenes/vamasa/pag_27.jpg', desc:'Sutura quirúrgica no absorbible de seda negra trenzada recubierta con silicona, calibre 3-0 y 4-0.', specs:['Calibre 3-0: aguja 19mm 3/8 círculo rev. cortante, hebra 45cm','Calibre 4-0: aguja 19mm 3/8 círculo rev. cortante, hebra 45cm','Caja con 12 sobres']},
{id:'vamasa-096', code:'47-SUGS0105', cat:'materiales', brand:'vamasa', name:'Sutura Surgeasy Absorbible', unit:'unidad', img:'imagenes/vamasa/pag_27.jpg', desc:'Sutura quirúrgica sintética absorbible de poliglicólido al 100%, calibre 3-0 y 4-0.', specs:['Calibre 3-0: aguja 19mm 3/8 círculo rev. cortante, hebra 68cm','Calibre 4-0: aguja 19mm 3/8 círculo rev. cortante, hebra 6/7cm','Absorción en 60 a 90 días']},
{id:'vamasa-097', code:'03-0THM', cat:'materiales', brand:'vamasa', name:'Tiras de fibra Ribbond', unit:'unidad', img:'imagenes/vamasa/pag_27.jpg', desc:'Tiras de fibra de polietileno para férulas y fracturas dentales, en 1, 2 y 3 mm de ancho.', specs:['1 tira de 1mm x 22cm incluye tijeras','1 tira de 2mm x 22cm incluye tijeras','1 tira de 3mm x 22cm incluye tijeras']},
{id:'vamasa-098', code:'03-SCIS', cat:'instrumental', brand:'vamasa', name:'Tijeras Ribbond', unit:'unidad', img:'imagenes/vamasa/pag_27.jpg', desc:'Tijeras especiales para corte de fibra Ribbond sin deshilachar el material.', specs:['1 pieza']},
